name: Renovate
on:
  push:
  # schedule:
  #   # The "*" (#42, asterisk) character has special semantics in YAML, so this
  #   # string has to be quoted.
  #   - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.1.6
        with:
          configurationFile: configs/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_AUTODISCOVER: false
          RENOVATE_REPOSITORIES: "renovate-test-project2"
          RENOVATE_PLATFORM: "github"
